@startuml
'https://plantuml.com/sequence-diagram




autonumber

actor User
control Controler
participant View
participant WorkLayer
database PostgresServer


==Authentication and Setup==

User -> Controler: Connect Request
Controler->View: Ask about existing account
View ->User:present the two option : connect or create account
User -> Controler : Choice
Controler -> User : Ask info
loop while it fail
  User->Controler: connexion data
  Controler -> PostgresServer:Connection info
  PostgresServer -> Controler : Validation
  Controler->View:Inform about result
  View->User:Confirm or ask a retry
end

User-> Controler:Choose a char
Controler->PostgresServer : Find available char or send a new char
PostgresServer -> Controler : Define starting map
Controler -> WorkLayer : Instantiate the map

==Gameplay Loop==
loop while not exit

alt regular action
    User->Controler :Action
    Controler->WorkLayer : Interpreted Action
    WorkLayer->PostgresServer : Update
    WorkLayer-> View: Display Result
    View-> User :Show result and display next options
else go through a door
    User ->Controler:Go through door
    Controler ->PostgresServer :Load new map
    PostgresServer-> Controler :send data
    Controler->WorkLayer :Interpret data
end
end



@enduml