--(Contenu_dialogue,id_personnage)


('A votre santé !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Ohbar')),
('Effectivement j''ai besoin d''aide, Toi l''amateur de bière j''ai besoin que tu ailles récupérer du bon houblon chez "Alain-Chichon", un fut chez "Maitre Kanter", et le dernier élement secret chez "Chie mi Hendrix"',(SELECT id_personnage FROM personnage WHERE nom_personnage='Ohbar')),
('Merci mon brave, voilà une bonne brune bien relevée. Bon chance !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Ohbar')),
('Héééééé, toi la bas, tu veux de la bonne ? ',(SELECT id_personnage FROM personnage WHERE nom_personnage='Alain Chichon')),
('Et voila mon brave, du bon houblon, n''en mets pas trop si tu veux pas planer. A bientôt. ',(SELECT id_personnage FROM personnage WHERE nom_personnage='Alain Chichon')),
('Bon vent !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Alain Chichon')),
('Hopla, qu''est ce que tu veux ici ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Maitre Kanter')),
('Ca joue, voila ton fut une fois !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Maitre Kanter')),
('Ok, barre toi alors wesh',(SELECT id_personnage FROM personnage WHERE nom_personnage='Maitre Kanter')),
('Salut fieu, j''ai concocté un gros paquet c''matin, t''en veux ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Chie mi Hendrix')),
('Tiens, v''la l''sachet !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Chie mi Hendrix')),
('Je te comprends, peace',(SELECT id_personnage FROM personnage WHERE nom_personnage='Chie mi Hendrix')),
('Bonjour mon enfant, tu veux une petite friandise ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Iggy Pope')),
('Tu devras aller chasser 4 chauves souris et les emener chez Durdur, pour qu''il te fabrique une Battte Ail.
Ensuite, tu devras combattre le terrible Jean Marie le PNJ, vivant dans le noir. Tu pourras me récuperer son œil en guise de trophée.',(SELECT id_personnage FROM personnage WHERE nom_personnage='Iggy Pope')),
('Si la prochaine fois, tu veux une friandise, tu viendras me voir dans le confessional,',(SELECT id_personnage FROM personnage WHERE nom_personnage='Iggy Pope')),
('Je vais te faire courir moi tu vas voir, n''est ce pas ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Jean Marie  le PNJ')),
('Vous êtes ici pour le Flouze ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Bernard tappir')),
('??',(SELECT id_personnage FROM personnage WHERE nom_personnage='Bernard tappir')),
('Oui mon gars , des nains pas plus haut que trois pommes m''ont volé ma bourbourse. Tu dois rencontrer Hippique-sous pour obtenir des informations',(SELECT id_personnage FROM personnage WHERE nom_personnage='Bernard tappir')),
('Bonjour monsieur, venez vous delester de vos picèes ici, je vous en prie !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Hippique-sous')),
('Et voilà la sauce du chef. Vous pourrez aller voir Durdur pour qu''il puisse vous forger une pièce rare, c''est un cadeau de Bernard. Bon courage.',(SELECT id_personnage FROM personnage WHERE nom_personnage='Hippique-sous')),
('Hallo ! Toi venir ici pour acheter armures ? Ja ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Durdur')),
('Ach so, vous vouloir grosse casquette à pointe traditionnelle de mein land! Moi avoir ça derrière gros comptoir, gut gut gut ! Vous vouloir lancer apfel sur ma grosse pointe ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Durdur')),
('Super gut, si toi atteindre ma pointe moi donner grosse boubourse ach,',(SELECT id_personnage FROM personnage WHERE nom_personnage='Durdur')),
('Ha sacré voleur de schleu, merci pour ton aide mein freund, voici un joli pull ovaire fait par ma fille,',(SELECT id_personnage FROM personnage WHERE nom_personnage='Bernard tappir')),
('Bonjour mon lapin, tu es la pour mes gros objets fétiches, hihihi ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Victoria-Big B ')),
('Tu devras prouver tes talents en combat singulier à l''arène, mais pas avec n''importe quelle arme mon lapin ! ',(SELECT id_personnage FROM personnage WHERE nom_personnage='Victoria-Big B ')),
('Vous revenez de chez Victoria Big-B ? ',(SELECT id_personnage FROM personnage WHERE nom_personnage='Bours-la')),
('Tu verras ou je vais te les mettres ses objets !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Bours-la')),
('Je suis en manque de vitesse, pouvez-vous m''aider ?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Die Anna')),
('J''ai besoin de récupérer une potion à Nana Moule Curry au restaurant in&out pour retrouver ma vitesse !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Die Anna')),
('J''ai vendu la dernière la potion au casino Scissor Palace, vous devriez peut être y faire un tour ! Pour me faire pardonner je voulaisse ces Musse Tongue',(SELECT id_personnage FROM personnage WHERE nom_personnage='Nana Moule Curry')),
('Tu as pu récupérer ma potion pour ma vitesse?',(SELECT id_personnage FROM personnage WHERE nom_personnage='Die Anna')),
('Super on va pouvoir aller visiter le tunnel en Musse Tongue maintenant !',(SELECT id_personnage FROM personnage WHERE nom_personnage='Die Anna'));

