--(id_lieu,nom_lieu,description_lieu,carte_lieu)

('1','Bad town','',''),
('2','la reine','',''),
('3','la bête','',''),
('4','scissor palace','',''),
('5','lennybar','',''),
('6','Profit-city','',''),
('7','black market','',''),
('8','lehman sisters','',''),
('9','place-2-B','',''),
('10','treump shop','',''),
('11','nainportnawak','',''),
('12','maxilase','',''),
('13','flunchbar','',''),
('14','park in son','',''),
('15','in & out','',''),
('16','ELF village','',''),
('17','msncircus','',''),
('18','pirate search','',''),
('19','daddy awards','',''),
('20','potatoe valley','','');
