('recuperer du houblon (Alain Chichon)',0),
('recuperer un fut (Maitre Kanter)',0),
('recuperer un élement secret (Chie mi Hendrix)',0),
('Aller tuer 4 chauves souris',0),
('Aller recuperer l''arme chez Durdur',0),
('Tuer Dracula (Jean Marie le PNJ)',0),
('Aller voir Hippique-sous pour avoir des infos',0),
('Donner des sousous à Durdur pour avoir une casquette à pointe afin de récupérer une boubourse à son concours de lancer de pommes',0),
('Retourner voir Benard Tappir et lui donner la boubourse gagner au concours de lancer de pomme',0),
('Combattre à l''arene',0),
('Choisir de tuer ou non Bours-La',0),
('Aller voir Nana Moule Curry pour récuperer la potion() a vendu la derniere potion au casino) elle lui donne une musse tongue à la place',0),
('rejoindre Lost Vegas au Scissor Palace',0),
('visiter le tunnel du pont en musse tongue avec Die Anna',0);
